[general]
fontname=Monospace 10
selchars=-A-Za-z0-9,./?%&#:_
scrollback=1000
bgcolor=#0f0f10101111
fgcolor=#d3d3d7d7cfcf
palette_color_0=#1d1d2c2c4747
palette_color_1=#d2d227275a5a
palette_color_2=#87875252baba
palette_color_3=#e1e155558181
palette_color_4=#1e1e5959aaaa
palette_color_5=#87875252baba
palette_color_6=#4b4b7676b8b8
palette_color_7=#e9e959598686
palette_color_8=#1d1d2c2c4747
palette_color_9=#ffff2f2f6b6b
palette_color_10=#b6b66e6efbfb
palette_color_11=#fbfb5f5f9898
palette_color_12=#2c2c8484fcfc
palette_color_13=#b5b56e6efafa
palette_color_14=#6767a2a2fdfd
palette_color_15=#fbfb8989adad
color_preset=Custom
disallowbold=false
boldbright=false
cursorblinks=false
cursorunderline=false
audiblebell=false
visualbell=false
tabpos=top
geometry_columns=80
geometry_rows=24
hidescrollbar=true
hidemenubar=true
hideclosebutton=false
hidepointer=false
disablef10=false
disablealt=false
disableconfirm=false

bgalpha=65535
tabwidth=100

[shortcut]
new_window_accel=<Primary><Shift>n
new_tab_accel=<Primary><Shift>t
close_tab_accel=<Primary><Shift>w
close_window_accel=<Primary><Shift>q
copy_accel=<Primary><Shift>c
paste_accel=<Primary><Shift>v
name_tab_accel=<Primary><Shift>i
previous_tab_accel=<Primary>Page_Up
next_tab_accel=<Primary>Page_Down
move_tab_left_accel=<Primary><Shift>Page_Up
move_tab_right_accel=<Primary><Shift>Page_Down
zoom_in_accel=<Primary><Shift>plus
zoom_out_accel=<Primary><Shift>underscore
zoom_reset_accel=<Primary><Shift>parenright
